name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: yarn install
      - name: Test
        run: yarn test

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
